version: "3.8"
services:
 postgres:
    image: postgres:14-alpine
    restart: "no"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: expense_tracker
    ports:
      - 5432:5432
